convention/urls.py
from django.conf.urls import url, include
from convention.views import reg, show_booking, participants_iframe, participants, checkin, seite, event_list, upload_attachment
from convention.api import router
from django.views.generic import TemplateView

app_name = "convention"
urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^$', event_list),
    url(r'^(?P<event_slug>.*)/reg/$', reg, name="reg"),
    url(r'^upload/$', upload_attachment, name="upload"),
    url(r'^(?P<event_slug>.*)/booking/$', show_booking, name="show-booking"),
    url(r'^(?P<event_slug>.*)/booking/(?P<booking_id>\d*)/checkin$', checkin, name="checkin"),
    url(r'^(?P<event_slug>.*)/booking/pdf/$', show_booking, { "pdf": True }, name="show-booking-pdf"),
    url(r'^(?P<event_slug>.*)/qr/$', show_booking, name="qr"),
    url(r'^(?P<event_slug>.*)/participants-iframe/$', participants_iframe, name="participants-iframe"),
    url(r'^(?P<event_slug>.*)/participants/$', participants, name="participants"),
    url(r'^(?P<event_slug>.*)/(?P<seite_slug>.*)/$', seite, name="seite"),
    url(r'^(?P<event_slug>.*)/$', seite, { "seite_slug": "home"}, name="home"),



]

convreg/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views.static import serve

admin.site.site_header = "Einrad-Events - Administration"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include("convention.urls")),
]

templates/base.html
{% load staticfiles %}
{% load l10n %}
<!doctype html>
<html ng-app="convReg">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>
            {% block fulltitle %}
                {{event.name}} - {% block title %}{% endblock %}
            {% endblock %}
        </title>

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/angular-xeditable/0.1.9/css/xeditable.css" rel="stylesheet">
        <link href="{% static "css/print.css" %}" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-2.1.4.min.js" type="text/javascript"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.6/i18n/angular-locale_de-de.js"></script>
        <script src="{% static "js/ui-bootstrap-tpls-3.0.6.min.js" %}"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-xeditable/0.1.9/js/xeditable.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-sanitize/1.5.8/angular-sanitize.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.16.2/lodash.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/restangular/1.5.2/restangular.min.js"></script>
        <script src="{% static "js/angular-validation-match.js" %}"></script>

        <style type="text/css">
            body { padding-top: 70px; }
        </style>
   
        <script type="text/javascript">
            angular.module("convReg", ["xeditable", "ui.bootstrap", "restangular", "ngSanitize", "validation.match" ])
                .config(["RestangularProvider", function(RestangularProvider) {
                    RestangularProvider.setBaseUrl("/api");
                    RestangularProvider.setRequestSuffix("/");
                }])
                .config(["$httpProvider", function($httpProvider) {
                    $httpProvider.defaults.xsrfCookieName = 'csrftoken';
                    $httpProvider.defaults.xsrfHeaderName = 'X-CSRFToken';
                }])
                .directive('checkRequired', function(){
                return {
                    require: 'ngModel',
                    restrict: 'A',
                    link: function (scope, element, attrs, ngModel) {
                    ngModel.$validators.checkRequired = function (modelValue, viewValue) {
                        var value = modelValue || viewValue;
                        var match = scope.$eval(attrs.ngTrueValue) || true;
                        return value && match === value;
                    };
                    }
                }; 
                })
                .controller("RegCtrl", [ "$scope", "$window", "Restangular", function($scope, $window, Restangular) {
                    var vm = this;
                    vm.reg = {};
                    vm.booking = {
                        essen: "all",
                        land: "DE",
                        anreise: null,
                        abreise: null,
                    }

                    vm.tshirts = {};
                    {% for tshirt in event.tshirts.all %}
                        vm.tshirts["{{tshirt.id}}"] = { label: "{{tshirt.groesse|escapejs}} (+ € {{tshirt.preis}})", preis: {{tshirt.preis|escapejs}} };
                    {% endfor %}

                    vm.anreise = [];
                    {% for anreise in event.anreise.all %}
                        vm.anreise.push({
                            tag: "{{anreise.tag|escapejs}}",
                            order: {{anreise.order|unlocalize}},
                            id: {{anreise.id|unlocalize}}
                        });
                    {% endfor %}

                    vm.tarif = {};
                    {% for tarif in event.tarife_buchbar.all %}
                        vm.tarif["{{tarif.id|unlocalize}}"] = {
                            tarif: "{{tarif.tarif|escapejs}}",
                            preis: {{tarif.preis|unlocalize}},
                            kostenstopp: {{tarif.kostenstopp|default:0|unlocalize}},
                        }
                        {% if forloop.first %}
                            vm.booking.tarif = "{{tarif.id|unlocalize}}";
                        {% endif %}
                    {% endfor %}

                    vm.abreise = [];
                    {% for abreise in event.abreise.all %}
                        vm.abreise.push({
                            tag: "{{abreise.tag|escapejs}}",
                            order: {{abreise.order|unlocalize}},
                            id: {{abreise.id|unlocalize}}
                        });
                    {% endfor %}      


                    vm.getPackages = function() {
                        Restangular.all("packages").getList({ event: {{event.id}} }).then(function(data) {
                            vm.packages = data;
                        });
                    };

                    vm.getSleep = function() {
                        Restangular.all("sleep").getList({ packages: vm.booking.paket.id }).then(function(data) {
                            vm.sleep = data;
                            if(vm.booking && vm.booking.schlafen)
                                vm.booking.schlafen = null;
                        });
                    };

                    vm.filterAbreise = function(value, index, array) {
                            if(vm.booking.anreise)
                        {
                            return(value.order > vm.booking.anreise.order);
                        }
                        else return false;
                    }

                    vm.calcSum = function() {
                        var sum = 0;

                        {% if event.paketsystem_nutzen %}
                            /* Paketbasierte, alte Variante */
                            if(vm.booking && vm.booking.paket)
                            {
                                sum += vm.booking.paket.preis;
                                if(vm.booking.schlafen)
                                    sum += vm.booking.schlafen.preis * vm.booking.paket.naechte;
                                if(vm.booking.bettwaesche)
                                    sum += 3;
                            }
                        {% else %}
                            /* Neue Variante nach Anreise, Abreise und Tarif */
                            if(vm.booking && vm.booking.tarif && vm.booking.anreise && vm.booking.abreise)
                            {
                                var preis = vm.tarif[vm.booking.tarif].preis;
                                var kostenstopp = vm.tarif[vm.booking.tarif].kostenstopp;
                                var tage = vm.booking.abreise.order - vm.booking.anreise.order;
                                sum = preis * tage;
                                if(kostenstopp && (kostenstopp < sum))
                                    sum = kostenstopp;
                            }
                        {% endif %}

                        if(vm.booking.tshirt)
                        {
                            var tshirt = vm.tshirts[vm.booking.tshirt];
                            sum += tshirt.preis;
                        }
                        return sum;
                    }

                    vm.submitBooking = function() {
                        data = angular.copy(vm.booking);

                        if(data.paket)
                            data.paket = data.paket.id;
                        if(data.schlafen)
                            data.schlafen = data.schlafen.id;
                        if(data.anreise)
                            data.anreise = data.anreise.id;
                        if(data.abreise)
                            data.abreise = data.abreise.id;

                        if(data.disziplinen)
                            data.disziplinen = Object.keys(data.disziplinen);

                        data.event = {{event.id}};
                        data.geburtsdatum = data.geburtsdatum.toISOString().slice(0, 10);

                        booking = Restangular.restangularizeElement(null, data, "booking");
                        vm.bookInProgress = true;
                        vm.bookError = false;
                        booking.save().then(function(data) {
                            vm.bookInProgress = false;
                            var url = "{% url "convention:show-booking" event.slug %}";
                            url += "?code="+ data.code + "&email=" + $window.encodeURIComponent(data.email);
                            $window.location.href = url;
                            
                        },
                        function() {
                            vm.bookError = true;
                            vm.bookInProgress = false;
                        });
                
                    }

                    vm.getPackages();

                    $scope.$watch(
                        function() {
                            if (vm.booking && vm.booking.paket)
                                return vm.booking.paket.id;
                        }, 
                        function(newVal) {
                            if(newVal)
                                vm.getSleep();
                        }
                    );

                    return; 
                }]);
        </script>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
            <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
               <div class="container">
                    <a class="navbar-brand" href="{% url "convention:seite" event.slug "home" %}">{{event.name}}</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                          </button>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="nav navbar-nav">
                            {% for seite in seiten %}
                                <a class="nav-item nav-link {% if active_page == seite.slug %}active{% endif %}"
                                    href="{% if seite.slug == "home" %}{% url "convention:home" event.slug %}{% else %}{% url "convention:seite" event.slug seite.slug %}{% endif %}">
                                        <i class="fa fa-{{seite.icon}} fa-fw"></i> {{seite.name}}
                                </a>
                            {% endfor %}
                            <a class="nav-item nav-link {% if active == 'participants' %}active{% endif %}"
                                href="{% url "convention:participants" event.slug %}">
                                    <i class="fa fa-users fa-fw"></i> Teilnehmer
                            </a>
                            {% if event.buchbar %}
                            <a class="nav-item nav-link {% if active == 'reg' %}active{% endif %}" href="{% url "convention:reg" event.slug %}"><i class="fa fa-pencil-alt"></i> Anmeldung</a>
                            {% endif %}
                        </div>
                        <div class="nav navbar-nav ml-auto">
                            <a class="nav-item nav-link {% if active == 'show-booking' %}active{% endif %}" href="{% url "convention:show-booking" event.slug %}"><i class="fa fa-eye"></i> Meine Buchung</a>
                        </div>
                    </div><!-- /.navbar-collapse -->
                </div>
            </nav>
            {% block outside %}{% endblock %}
            <div class="container">
                {% block content %}{% endblock %}
                <hr>
                <div class="text-center card bg-secondary text-white">
                    <div class="card-body">
                    <h3>Fragen zum Event?</h3>
                    <p>Dein Ansprechpartner {{event.ansprechpartner}} hilft dir gern weiter:</p>
                    <h3><a href="mailto:{{event.contact}}" class="btn btn-dark btn-lg"><i class="fa fa-envelope"></i> {{event.kontakt}}</a></h3>
                    </div>
                </div>
            </div>
        {% endblock body %}
    </body>
</html>