convention/urls.py
from django.conf.urls import url, include
from convention.views import reg, show_booking, participants_iframe, participants, checkin, seite, event_list, upload_attachment
from convention.api import router
from django.views.generic import TemplateView

app_name = "convention"
urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^$', event_list),
    url(r'^(?P<event_slug>.*)/reg/$', reg, name="reg"),
    url(r'^upload/$', upload_attachment, name="upload"),
    url(r'^(?P<event_slug>.*)/booking/$', show_booking, name="show-booking"),
    url(r'^(?P<event_slug>.*)/booking/(?P<booking_id>\d*)/checkin$', checkin, name="checkin"),
    url(r'^(?P<event_slug>.*)/booking/pdf/$', show_booking, { "pdf": True }, name="show-booking-pdf"),
    url(r'^(?P<event_slug>.*)/qr/$', show_booking, name="qr"),
    url(r'^(?P<event_slug>.*)/participants-iframe/$', participants_iframe, name="participants-iframe"),
    url(r'^(?P<event_slug>.*)/participants/$', participants, name="participants"),
    url(r'^(?P<event_slug>.*)/(?P<seite_slug>.*)/$', seite, name="seite"),
    url(r'^(?P<event_slug>.*)/$', seite, { "seite_slug": "home"}, name="home"),



]

convreg/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.views.static import serve

admin.site.site_header = "Einrad-Events - Administration"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include("convention.urls")),
]

convention/models.py
# +-+ coding: utf-8 +-+



from django.db import models
import random
import string
from django.utils import timezone
from django.urls import reverse
from django.utils.http import urlencode
from localflavor.generic.models import IBANField, BICField
from ckeditor_uploader.fields import RichTextUploadingField
from django_countries.fields import CountryField
from datetime import date
from dateutil.relativedelta import relativedelta

# Create your models here.

SCHLAFEN_CHOICES = (
    ("none", "Keiner"),
    ("floor", "Auf dem Boden"),
    ("dorm", "Bett im Schlafsaal"),
    ("four", "Bett im Viererzimmer"),
    ("dbl", "Bett im Doppelzimmer "),
    ("dbl_ensuite", "Bett im Doppelzimmer Du/WC"),
)

ESSEN_CHOICES = (
    ("all", "alles"),
    ("v", "vegetarisch"),
    ("vv", "vegan"),
)

PAKET_CHOICES = (
    ("all", "All inclusive"),
    ("late", "All inclusive - Spätanreise"),
    ("day", "Tagesgast"),
)

STATUS_CHOICES = (
    ("open", "Offen"),
    ("progress", "In Bearbeitung"),
    ("confirmed", "Bestätigt"),
    ("problem", "Problem - Teilnehmer kontaktiert"),
    ("canceled", "Storno"),
)

GESCHLECHT_CHOICES = (
    ("f", "weiblich"),
    ("m", "männlich"),
    ("d", "divers"),
)

class Event(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField("Kürzel", help_text="Kürzel für die URL, nur Buchstaben, Zahlen und Striche, keine Leerzeichen, z.B. 'odm-steinach-2017'", unique=True)
    von = models.DateTimeField()
    bis = models.DateTimeField()
    beschreibung = models.TextField()
    buchbar = models.BooleanField(default=True, help_text="Event derzeit buchbar")

    kontakt = models.EmailField("E-Mail-Kontakt")
    ansprechpartner = models.CharField("Name", max_length=100)
    ausrichter = models.CharField(help_text="Name des Ausrichters, z.B. 'SV Pusemuckel'", max_length=100)

    paypal = models.EmailField("PayPal-Adresse", help_text="An diese Adresse werde Zahlungen gesendet", blank=True)
    kontoinhaber = models.CharField(max_length=100, blank=True)
    bic = BICField("BIC", blank=True)
    iban = IBANField("IBAN", blank=True)

    adresse = models.BooleanField("Adresse erforderlich", help_text="Ist bei der Anmeldung die Eingabe der Postadresse erforderlich?", default=False)
    telefon = models.BooleanField("Telefon erforderlich", help_text="Ist bei der Anmeldung die Eingabe einer (Notfall-)Telefonnummer erforderlich?", default=False)
    geschlecht  = models.BooleanField("Geschlecht erforderlich", help_text="Ist bei der Anmeldung die Eingabe des Geschlechts erforderlich?", default=False)

    verpflegung = models.BooleanField("Verpflegung", help_text="Es wird Verpflegung angeboten", default=True)
    vegetarisch = models.BooleanField("Vegetarisch", help_text="Es kann vegetarisches Essen gewählt werden.", default=True)
    vegan = models.BooleanField("Vegan", help_text="Es kann veganes Essen gewählt werden.", default=True)
    vegan_breakfast_only = models.BooleanField("Nur veganes Frühstück", help_text="Der Benutzer wird bei der Buchung darauf hingewiesen, dass nur das Frühstück vegan ist.", default=False)

    paketsystem_nutzen = models.BooleanField("Paketsystem nutzen", help_text="Teilnehmer können verschiedene Pakete benutzen (altes System).", default=True)

    admin = models.ForeignKey("auth.User", on_delete=models.CASCADE, help_text="Dieser Benutzer kann das Event verwalten")

    def get_absolute_url(self):
        return reverse("convention:seite", args=[self.slug])

    def __str__(self):
        return self.name

    @property
    def anreise(self):
        return self.tage.filter(anreise=True)

    @property
    def abreise(self):
        return self.tage.filter(abreise=True)

    @property
    def tarife_buchbar(self):
        return self.tarife.filter(buchbar=True)


    class Meta:
        verbose_name = "Event"
        verbose_name_plural = "Events"
        ordering = ("von", "name")  

class Tarif(models.Model):
    event = models.ForeignKey("Event", related_name="tarife", on_delete=models.CASCADE)
    tarif = models.CharField(max_length=100)
    preis = models.DecimalField("Preis pro Nacht", max_digits=8, decimal_places=2, null=True, blank=True)
    kostenstopp = models.DecimalField("Kostenstopp", max_digits=8, decimal_places=2, null=True, blank=True)
    buchbar = models.BooleanField("Aktuell buchbar", default=True)

    order = models.PositiveIntegerField("Sortierung", default=0)

    def __str__(self):
        return self.tarif

    class Meta:
        ordering = ("order", "tarif")

class Dokument(models.Model):
    event = models.ForeignKey("Event", related_name="dokumente", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    dokument = models.FileField("Dokument", upload_to="dokumente")
    u18 = models.BooleanField("U18", default=False, help_text="Nur relevant für Personen unter 18 Jahren.")
    upload = models.BooleanField("Upload für Rücksendung", default=False, help_text="Dokument muss zurückgesendet werden über die Upload-Funktion.")
    order = models.PositiveIntegerField("Sortierung", default=0)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Dokument"
        verbose_name_plural = "Dokumente"
        ordering = ("order", "name")

def anhang_path(instance, filename):
    return "attachments/%s/%s" % (instance.booking.code, filename)

class Anhang(models.Model):
    booking = models.ForeignKey("Booking", on_delete=models.CASCADE)
    dokument = models.ForeignKey("Dokument", on_delete=models.CASCADE)
    datei = models.FileField(upload_to=anhang_path)
    datum = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("booking", "dokument")
        verbose_name = "Anhang"
        verbose_name_plural = "Anhänge"

class TShirt(models.Model):
    event = models.ForeignKey("event", on_delete=models.CASCADE, related_name="tshirts")
    groesse = models.CharField("Größe", max_length=100)
    preis = models.DecimalField("Aufpreis", max_digits=8, decimal_places=2, default=0)
    order = models.PositiveIntegerField("Sortierung", default=0)

    def __str__(self):
        return self.groesse

    class Meta:
        verbose_name = "T-Shirt"
        verbose_name_plural = "T-Shirts"
        ordering = ("order", "groesse")

class Tag(models.Model):
    event = models.ForeignKey("event", on_delete=models.CASCADE, related_name="tage")
    tag = models.CharField("Tag", max_length=100)

    anreise = models.BooleanField("Anreise möglich", default=False)
    abreise = models.BooleanField("Abreise möglich", default=False)
    
    order = models.PositiveIntegerField("Sortierung", default=0)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tage"
        ordering = ("order", "tag")

class Disziplin(models.Model):
    event = models.ForeignKey("event", on_delete=models.CASCADE, related_name="disziplinen")
    code = models.CharField(max_length=10)
    label = models.CharField(max_length=100)
    order = models.PositiveIntegerField("Sortierung", default=0)

    def __str__(self):
        return self.label
    
    class Meta:
        verbose_name = "Disziplin"
        verbose_name_plural = "Disziplinen"
        ordering = ("order", "code")

class Seite(models.Model):
    event = models.ForeignKey("Event", on_delete=models.CASCADE, related_name="seiten")
    slug = models.SlugField(default="home")
    name = models.CharField(max_length=30)
    icon = models.CharField(max_length=30, default="home")
    html = RichTextUploadingField(blank=True, null=True)
    order = models.PositiveIntegerField(default=0)
    menu = models.BooleanField("Sichtbar im Menü", default=True)

    class Meta:
        verbose_name = "Seiten"
        verbose_name_plural = "Seiten"
        unique_together = ("event", "slug")
        ordering = ("order",)


def generate_code():
    return "".join(random.choice(string.ascii_lowercase+string.digits) for i in range(8))

class Booking(models.Model):
    event = models.ForeignKey("Event", on_delete=models.CASCADE)
    code = models.CharField(max_length=8, unique=True, default=generate_code)
    datum = models.DateTimeField(auto_now_add=True)
    checkin = models.DateTimeField(null=True, blank=True, editable=False)

    vorname = models.CharField("Vorname", max_length=100)
    nachname = models.CharField("Nachname", max_length=100)
    geschlecht = models.CharField("Geschlecht", max_length=1, choices=GESCHLECHT_CHOICES, null=True, blank=True)

    email = models.EmailField("E-Mail")
    verein_ort = models.CharField("Verein oder Ort", max_length=100, blank=True)
    geburtsdatum = models.DateField()

    adresse = models.CharField(max_length=255, blank=True, null=True)
    plz = models.CharField("PLZ", max_length=20, blank=True, null=True)
    ort = models.CharField(max_length=100, blank=True, null=True)
    land = CountryField(default="DE", blank=True, null=True)
    telefon = models.CharField(max_length=20, blank=True, null=True)

    paket = models.ForeignKey("Package", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Paket")
    schlafen = models.ForeignKey("Sleep", on_delete=models.SET_NULL, verbose_name="Schlafplatz", null=True, blank=True)

    essen = models.CharField("Verpflegung", max_length=15, choices=ESSEN_CHOICES)
    tshirt = models.ForeignKey("TShirt", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="T-Shirt")
    anreise = models.ForeignKey("Tag", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Anreise", related_name="booking_anreise")
    abreise = models.ForeignKey("Tag", null=True, blank=True, on_delete=models.SET_NULL, verbose_name="Abreise", related_name="booking_abreise")
    tarif = models.ForeignKey("Tarif", null=True, blank=True, on_delete=models.SET_NULL)
    disziplinen = models.ManyToManyField("convention.Disziplin", null=True, blank=True)



    anmerkungen = models.TextField("Anmerkungen", blank=True)

convention/views.py
# +-+ coding: utf-8 +-+

from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from convention.models import Package, Booking, Transaction, Event, Seite, Anhang
from convention.forms import BookingViewForm, AnhangForm
from django.db.models import F, Sum
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from django.utils.http import urlencode, urlquote
from django.utils import timezone
#from django_xhtml2pdf.utils import generate_pdf
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from weasyprint import HTML
from django.core.exceptions import PermissionDenied

# Create your views here.

def event_list(request):
    context = {
        "event_list": Event.objects.filter(von__gt=timezone.now()),
    }
    return render(request, "convention/event_list.html", context)

def seite(request, event_slug, seite_slug):
    seite = get_object_or_404(Seite, slug=seite_slug, event__slug=event_slug)
    context = {
        "seite": seite,
        "active_page": seite.slug,
        "event": seite.event,
        "seiten": seite.event.seiten.filter(menu=True),

    }
    return render(request, "convention/seite.html", context)

def participants_iframe(request, event_slug):
    event = get_object_or_404(Event, slug=event_slug)

    context = {
        "bookings": Booking.objects.filter(event=event).order_by("datum"),
        "event": event,
        "seiten": event.seiten.filter(menu=True),

    }
    return render(request, "convention/participants_iframe.html", context)

# iframe with participants list for the main site
def participants(request, event_slug):
    event = get_object_or_404(Event, slug=event_slug)

    context = {
        "bookings": Booking.objects.filter(event=event).order_by("nachname", "vorname"),
        "event": event,
        "seiten": event.seiten.filter(menu=True),

        "active": "participants",
    }
    return render(request, "convention/participants.html", context)


@login_required
def checkin(request, event_slug, booking_id):
    event = get_object_or_404(Event, slug=event_slug)

    booking = get_object_or_404(Booking, pk=booking_id)
    booking.checkin = timezone.now()
    booking.save()
    return redirect(booking)
        

# registration
def reg(request, event_slug):
    event = get_object_or_404(Event, slug=event_slug)
    if not event.buchbar:
        raise PermissionDenied()

    context = {
        "active": "reg",
        "event": event,
        "seiten": event.seiten.filter(menu=True),

    }

    return render(request, "convention/reg.html", context)

def upload_attachment(request):
    form = AnhangForm(request.POST, request.FILES)
    if form.is_valid():
        cd = form.cleaned_data
        booking = cd["booking"]
        dokument = cd["dokument"]
        datei = cd["datei"]
        anhang, created = Anhang.objects.get_or_create(booking=booking, dokument=dokument, defaults={"datei": datei})
        if not created:
            anhang.datei = datei
            anhang.save()

        return redirect(booking)
    else:
        raise PermissionDenied()

# show booking and PP return / cancel page
@csrf_exempt
def show_booking(request, event_slug, pdf=False):
    event = get_object_or_404(Event, slug=event_slug)

    booking = None

    if "code" in request.GET:
        form = BookingViewForm(request.GET)
        if form.is_valid():
            booking = form.instance
    else:
        form = BookingViewForm()

    bezahlt = 0
    offen = 0
    
    if booking:
        offen = booking.betrag
        aggr = booking.transaction_set.all().aggregate(bezahlt=Sum("betrag"))
        bezahlt = aggr["bezahlt"] or 0
        offen = booking.betrag - bezahlt
   
    transactions = None
    dokumente = None
    dokumente_fehlend = None
    qr_url = None
    print_url = None
    if booking:
        transactions = booking.transaction_set.all().order_by("datum")
        
        if booking.volljaehrig():
            dokumente = booking.event.dokumente.exclude(u18=True)
        else:
            dokumente = booking.event.dokumente.all()
        dokumente_fehlend = dokumente.filter(upload=True).exclude(anhang__booking=booking)

        for dok in dokumente:
            dok.anhang = dok.anhang_set.filter(booking=booking).first()

        qr_url = urlquote(request.build_absolute_uri(reverse("convention:qr", args=[event.slug])+"?"+urlencode({ "code": booking.code, "email": booking.email })))
        print_url = reverse("convention:show-booking-pdf", args=[event.slug])+"?"+urlencode({ "code": booking.code, "email": booking.email })

    # PayPal
    # What you want the button to do.
    paypal_form = None

    if booking and offen > 0:
        paypal_dict = {
            "business": event.paypal,
            "amount": offen,
            "currency_code": "EUR",
            "lc": "DE",
            "item_name": "%s %s" % (event.name, booking.code.upper()),
            "custom": booking.code.upper(),
            "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
            "return_url": request.build_absolute_uri(booking.get_absolute_url()),
            "cancel_return": request.build_absolute_uri(booking.get_absolute_url()),
        }

        # Create the instance.
        paypal_form = PayPalPaymentsForm(initial=paypal_dict)

    context = {
        "event": event,
        "seiten": event.seiten.filter(menu=True),
        "form": form,
        "booking": booking,
        "bezahlt": bezahlt,
        "offen": offen,
        "transactions": transactions,
        "dokumente": dokumente,
        "dokumente_fehlend": dokumente_fehlend,
        "qr_url": qr_url,
        "print_url": print_url,
        "active": "show-booking",
        "paypal_form": paypal_form,
    }

    if pdf:
        html = render_to_string("convention/booking_pdf.html", context=context, request=request)
        pdf = HTML(string=html).write_pdf()
        resp = HttpResponse(pdf, content_type='application/pdf')

        return resp
    else:
        return render(request, "convention/booking.html", context)

convention/templates/convention/booking_pdf.html
<!-- 
This is intended to be rendered to a PDF using pisa, not in a browser.
Therefore, the HTML and CSS here can look a bit fishy. Please refer to 
http://www.htmltopdf.org/doc/pisa-en.html for reference 
-->
<html>
<style>
/*Custom fonts*/
/*@font-face {
    font-family: Weird, "Weird Font";
    src: url(test/weird.ttf)
}
@font-face {
    font-family: Akkurat;
    src: url(test/Akkurat.ttf)
}
@font-face {
    font-family: Akk;
    src: url(test/akk.otf)
}*/
/* Page layout */
body {
    font-family: sans-serif;
    font-size:10pt;
}
@page {
    size: a4 portrait;
    margin: 2cm;
}
h1, h2, h3, h4 { /* Don't add an outline to the document */
    -pdf-outline: false;
}
.border {
    border-top-width: 1px;
    border-bottom-width: 1px;
    border-left-width: 1px;
    border-right-width: 1px;
    
    border-top-style: solid;
    border-bottom-style: solid;
    border-left-style: solid;
    border-right-style: solid;
}
.top_image {
    zoom: 80%;
}
</style>
<body>
    <p align="center" style="font-size:14px">
        <strong>{{event.name}}: Deine Buchung</strong> - eingegangen am {{booking.datum|date:"SHORT_DATETIME_FORMAT"}}
    </p>
    <p align="center" style="font-size:14px">
        <strong>DIESES TICKET BITTE AUSDRUCKEN UND BEIM CHECK-IN VORZEIGEN</strong>
    </p>
    <hr>
    <table width="100%">
        <tr style="padding-top:0.2cm;padding-bottom:0">
            <td width="30%" align="center" valign="top">
                <div style="font-size:24pt;font-weight:bold">{{ booking.code|upper }}</div>
            </td>
            <td align="right">
                <div style="font-size:20pt">
                    {{booking.nachname|slice:":10"|upper}}
                    {% if event.paketsystem_nutzen %}
                        {{booking.paket}} {{booking.schlafen|default:"NOSLEEP"}}
                    {% else %}
                        {{booking.tarif|upper|slice:"5"}} {{booking.anreise|upper|slice:"2"}}-{{booking.abreise|upper|slice:"2"}}
                    {% endif %}
                </div>
            </td>
        </tr>
        <tr style="border-top:1pt black solid;padding-top:0.3cm;margin-top:0">
            <td width="30%" align="center" valign="top">
                <img align="left" src="https://chart.googleapis.com/chart?chs=200x200&cht=qr&chld=L&chl={{qr_url}}">
            </td>
            <td width="70%" valign="top">
                
                <div class="border" style="padding:0.2cm">
                    <i class="fa fa-user fa-fw"></i> <strong>{{booking.vorname}} {{booking.nachname}}</strong>{% if booking.geschlecht %}, {{booking.get_geschlecht_display}}{% endif %}, {{booking.geburtsdatum|date}}{% if booking.verein_ort %}, {{booking.verein_ort}}{% endif %}<br>
                    <i class="fa fa-envelope fa-fw"></i> {{booking.email}}<br>
                    <i class="fa fa-info fa-fw"></i> Buchungscode <strong>{{booking.code|upper}}</strong> (bitte notieren)<br>
                    <i class="fa fa-book fa-fw"></i>
                            {% if event.paketsystem_nutzen %}{{booking.paket.kurz}}{% else %}Tarif: {{booking.tarif}}{% endif %}
                        <br>
                    {% if event.paketsystem_nutzen %}
                    <i class="fa fa-bed fa-fw"></i> 
                            {{booking.schlafen.name|default:"Keine Übernachtung"}}
                        <br>
                    {% endif %}
                    {% if event.verpflegung %}
                    Essen: {{ booking.get_essen_display }}
                    {% endif %}
                    <br>
                    {% if booking.tshirt %}T-Shirt: {{booking.tshirt}} (+ € {{booking.tshirt.preis}})<br>{% endif %}
                    {% if booking.anreise %}Anreise: {{booking.anreise}}<br>{% endif %}
                    {% if booking.abreise %}Abreise: {{booking.abreise}}<br>{% endif %}

                    {% if booking.anmerkungen %}<br>Anmerkungen: {{booking.anmerkungen}}{% endif %}
                </div>
            </td>
        </tr>
    </table>
    <hr>
    <div style="font-size:1.4em;padding-top:0.2cm" class="row">
        <table width="100%" style="width:100%">
            <tr>
                <td>
                    Status: 
                    {{ booking.get_status_display|upper }}
                </td>
                <td align="center">
                    Gesamtbetrag: 
                    € {{booking.betrag}}
                </td>
                <td align="right">
                    Noch zu zahlen: 
                    € {{offen}}
                </td>
            </tr>
        </table>
    </div>
    <hr>
   
    <h4>Zahlungsverlauf</h4>
    <table class="table table-condensed table-striped" style="width:100%">
        <thead>
            <tr>
                <th align="left">Datum</th>
                <th align="left">Bemerkung</th>
                <th align="right">Betrag</th>
            </tr>
        </thead>
        <tbody>
            {% if not transactions %}
                <tr><td colspan=3 class="text-center">- Bisher keine Zahlungen von dir erhalten -</td></tr> 
            {% endif %}
            {% for t in transactions %}
                <tr>
                    <td>{{t.datum|date:"SHORT_DATETIME_FORMAT"}}</td>
                    <td>
                        {{t.get_typ_display}} 
                        {% if not t.mittel == "internal" %}
                            via {{t.get_mittel_display}}
                        {% endif %}
                        {% if t.grund %}
                            <br><small class="text-info">{{t.grund}}</small>
                        {% endif %}
                    </td>
                    <td align="right">€ {{t.betrag}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>

            <h4>Bankverbindung für Zahlungen</h4>
            <small>
            <table>
                <tr>
                    <td>Kontoinhaber</td><td>{{event.kontoinhaber}}</td>
                </tr>
                <tr>
                    <td>Verwendungszweck</td><td>{{booking.code|upper }} {{booking.vorname|upper}} {{booking.nachname|upper}}</td>
                </tr>
                <tr>
                    <td>Betrag</td><td>€ {{offen}}</td>
                </tr>
                <tr>
                    <td>IBAN</td><td>{{event.iban}}</td>
                </tr>
                <tr>
                    <td>BIC</td><td>{{event.bic}}</td>
                </tr>
            </table>
            </small>
    <hr>


        
</body>
</html>

convention/templates/convention/event_list.html
 {% extends "base.html" %} {% load bootstrap3 %} {% load staticfiles %} 

 {% block fulltitle %}Uniconvention.com - buch dein Einrad-Event!{% endblock %}
 
 {% block body %}   
<div class="jumbotron">
    <div class="container">

        <h1>Einrad-Events buchen</h1>
        <p>
            Willkommen bei uniconvention.com, dem neuen Buchungsportal für Einrad-Events. Wähle einfach ein Event aus der Liste und melde
            dich an!
        </p>
    </div>
</div>
<div class="container">
    <div class="row">
        <table class="table table-striped">
            <tbody>
                {% for event in event_list %}
                <tr>
                    <td class="clearfix">
                        <p class="float-right">
                            <em>{{event.von|date:"SHORT_DATETIME_FORMAT"}} - {{event.bis|date:"SHORT_DATETIME_FORMAT" }}</em><br>
                            <strong>{{event.ausrichter}}</strong>
                        </p>
                        <h4>{{event}}</h4>
                        <p>{{event.beschreibung}}</p>

                        <a target="_blank" class="btn btn-primary float-right" href="{% url "convention:home" event.slug %}">
                            <i class="fa fa-pencil"></i> Weitere Infos &amp; Anmeldung
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

convention/templates/convention/participants.html
{% extends "base.html" %}

{% block content %}
<h1>Teilnehmer</h1>

<div class="table-responsive">
    <table class="table table-hover table-sm table-striped">
        <tr>
            <th>Nachname</th>
            <th>Vorname</th>
            <th>Verein / Ort</th>
        </tr>
        {% for b in bookings %}
            <tr>
                <td>{{b.nachname}}</td><td>{{b.vorname}}</td><td>{% if b.verein_ort %}{{b.verein_ort}}{% endif %}</td>
            </tr>
        {% endfor %}
    </table>

</div>
{% endblock %}

convention/templates/convention/participants_iframe.html
<ol>
{% for b in bookings %}
    <li>{{b.vorname}} {{b.nachname}}{% if b.verein_ort %}, {{b.verein_ort}}{% endif %}</li>
{% endfor %}
</ol>

convention/templates/convention/program.html
{% extends "base.html" %}

{% block outside %}
<iframe style="border:0;padding:0;margin:0;margin-top:-20px" src="https://docs.google.com/spreadsheets/d/1dKacxGtqh89YbXQCW-92Q7MdMEvOP50ojx07PSRqQD0/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="1550"></iframe>
{% endblock %}

convention/templates/convention/seite.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{seite.name}}{% endblock %}
{% block head %}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>


{% endblock %}
{% block content %}
    {{seite.html|safe}}

{% endblock %}